name: assignment
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev




version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #font
  google_fonts: ^6.2.1
  #video player
  video_player: ^2.8.6
  #cache manger
  flutter_cache_manager: ^3.3.2
  cached_network_image: ^3.3.1
  # gradient
  gradient_borders: ^1.0.0
  # state
  get: ^4.6.6
  #http
  http: ^1.2.1
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
